#!/bin/zsh

ANTIGEN=$HOME/.antigen/
# Antigneがなければ落としてくる
[ -f $ANTIGEN/antigen.zsh ] || git clone\
  https://github.com/zsh-users/antigen.git $ANTIGEN
if [[ -f $ANTIGEN/antigen.zsh ]]; then
  source $ANTIGEN/antigen.zsh
  antigen use oh-my-zsh

  # antigen update
  # antigen selfupdate
  #
  if [ "$OSTYPE"="darwin16.0" ]; then
    antigen bundle osx
    antigen bundle https://github.com/iam4x/zsh-iterm-touchbar
    antigen bundle iterm-tab-colors
    antigen bundle iterm-touchbar
    antigen bundle brew

    source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
  fi

antigen bundle git
antigen bundle git-extras # Enables the zsh completion from git
antigen bundle autojump
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle adb
antigen bundle command-not-found
antigen theme robbyrussell
antigen apply

#Manage java ativate versions
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
fi
