#!/bin/zsh

ANTIGEN=$HOME/.antigen/
# Antigneがなければ落としてくる
[ -f $ANTIGEN/antigen.zsh ] || git clone\
  https://github.com/zsh-users/antigen.git $ANTIGEN
if [[ -f $ANTIGEN/antigen.zsh ]]; then
  source $ANTIGEN/antigen.zsh
  antigen use oh-my-zsh

  # antigen update
  # antigen selfupdate
  #
  if [[ "$(uname)" == "Darwin" ]]; then
    antigen bundle osx
    antigen theme https://github.com/iam4x/zsh-iterm-touchbar
    antigen bundle iterm-tab-colors
    # antigen bundle iterm-touchbar
    antigen bundle brew
    antigen bundle zsh-users/zsh-autosuggestions
  fi

antigen bundle git
antigen bundle git-extras # Enables the zsh completion from git
antigen bundle autojump
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle adb
antigen bundle command-not-found
antigen bundle rails
antigen bundle rspec
antigen bundle docker
antigen bundle docker-compose
antigen theme robbyrussell
antigen apply

#Manage java ativate versions
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


#enable dotnet autocomplete
_dotnet_zsh_complete()
{
  local completions=("$(dotnet complete "$words")")

  reply=( "${(ps:\n:)completions}" )
}

compctl -K _dotnet_zsh_complete dotnet

#set locale lang
export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8

export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$PATH:$ANDROID_HOME/tools"
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" export PATH="/usr/local/opt/qt/bin:$PATH"
export PATH="/Users/ricardobranco/Qt5.5.0/5.5/clang_64/bin/:$PATH"
export PATH="$HOME/.rbenv/shims:$PATH"
export PATH="/usr/local/sbin:$PATH"
